server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notvis
    username: notvis
    password: notvis
    driver-class-name: org.postgresql.Driver



  jpa:
    hibernate:
      ddl-auto: create #Quando acabar os testes não posso esquecer de mudar para 'update'!!!!!! importantissimo
    show-sql: true
    properties:
      hibernate:
        default_schema: notvis_schema
        format_sql: true

  mvc:
    hiddenmethod:
      filter:
        enabled: true

# Se você adicionou springdoc:
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
